### ISSUE TITLE
Is "Skolemizingblank nodes with Hash URIs" (#1187) a breaking change?

### ISSUE THREAD

**Issue by kefo** [fcrepo/fcrepo#1188] opened 2017-04-13 17:17 UTC
This is to flesh out whether [PR 1187](https://github.com/fcrepo4/fcrepo4/pull/1187), which fixes https://jira.duraspace.org/browse/FCREPO-2108, constitutes a breaking change.  If not, then it could be released as ~~4.8.0~~ 4.7.x.

See discussion here:
- Minutes:  https://wiki.duraspace.org/display/FF/2017-04-13+-+Fedora+Tech+Meeting
- Comment: https://wiki.duraspace.org/display/FF/2017-04-13+-+Fedora+Tech+Meeting?focusedCommentId=83236786#comment-83236786

A few notes (extracted from above and added):  

- It does not appear to make any change to the published Fedora API.
- Existing resources will not change, but hash uris would be used for new resources employing blank nodes
- Deleting a resource that used a blank node, leaves the .well-known URI behind in the repository.
- It is possible to `curl -X DELETE` a .well-known resource (a blank node) and remove *only* the .well-known resource (blank node). `curl -X DELETE' against a hash URI will of course delete the 'parent' resource, not just that 'hash'ed resource.
- It is possible to GET a .well-known URI and *only* receive a representation of the .well-known resource.  This change means a client might get unexpected (more verbose) output from a GET against a 'hash' uri.

The last three points raise issues when a client encounters unexpected behavior from the current implementation.

**Comment by tpendragon** [comment] 2017-04-13 18:20
Hydra doesn't use blank nodes in FCREPO specifically because of the difficulty in handling the `.well-known` behavior. So, :+1: for minor release from me.

**Comment by christopher-johnson** [comment] 2017-04-14 05:33
FYI: This change will break my downstream JSON-LD implementation of blank nodes to create ordered lists with the fromRDF method.   The way that the JSON-LD  processor creates @lists from RDF depends on the conventional bnode _:string representation in the RDF.   So, I have patched the JSON-LD library with a simple function that parses subjects and objects for the .well-known prefix and rewrites the URI as a _:.  This method can probably be adapted to the new #genid convention.  From my point of view, the critical thing is that there is a standard semantic that identifies an internal resource representaion as a blank node that can be made anonymous again in downstream processors.  I have yet to test my implementation with #1187

**Comment by christopher-johnson** [comment] 2017-04-14 07:38
I am testing this and have found that 4.8.0 (somehow) changes the expectations of acrepo-connector-triplestore.  @acoburn may know more about the cause.  I do not know if this constitutes a breaking change, but for me, it no longer works.  I will continue to investigate.

**Comment by awoods** [comment] 2017-04-14 15:56
As a note, @christopher-johnson , the `master` branch of fcrepo4 includes a couple of other "breaking change" commits, which likely are playing a role in the behavior you are seeing. 
If we were to do a 4.8.0 release, it would involve a port of https://github.com/fcrepo4/fcrepo4/pull/1187 to the [4.7-maintenance](https://github.com/fcrepo4/fcrepo4/tree/4.7-maintenance) branch.

**Comment by kefo** [comment] 2017-04-14 20:52
@christopher-johnson So you believe this could be a minor release versus part of a major release?

**Comment by acoburn** [comment] 2017-04-14 20:56
Can someone remind me what "major release" means? Does that mean 4.8.0?

**Comment by kefo** [comment] 2017-04-14 22:15
Right.  I suddenly find myself confused too.

Harking back, I believe we agreed that semantic versioning does not officially start until release 5.0, which would be when the software aligns with the API.  If that is correct, then "major release" in this sense (that is, a breaking change) would warrant a 4.8.0 release.  A non-breaking change would result in the next 4.7.x release (and perhaps back-ported to 4.6.x?).  But I though it had been decided there would be no "major" release until later this year. 

If what I just wrote is accurate, it means I was wrong in the opening post to this Issue.  I should have written 4.7.x (I updated the original above).

It seems that @awoods has opened the door to a 4.8.0 release in his [comment above](https://github.com/fcrepo4/fcrepo4/issues/1188#issuecomment-294179241) and that, in such a scenario, this particular PR would be backported to 4.7.x.  In that situation, however, I would think this PR had been deemed backwards compatible and therefore we could just release a 4.7.x.

**Comment by acoburn** [comment] 2017-04-14 22:28
Thanks, @kefo, that makes sense.

**Comment by awoods** [comment] 2017-04-17 02:43
Yes, @kefo, I was in the semantic versioning mindset when I mentioned 4.8.0 above (meaning a minor release)... I have also updated my comment for clarity.
We will stick with the non-semantic approach until 5.0.0.

**Comment by christopher-johnson** [comment] 2017-04-17 06:00
Since the existing .well-known representation is not documented as part of the API, I do not think that modifying it can be a considered a breaking change (as per semver).  However, I think that #1187 can be leveraged towards documenting it as a standard for internal (skolemized) resource representation sourced from RDF that contains anonymous resources.  And creating a new documented standard could be significant for the community who may build implementations that depend on it, particularly in the context of "ordering RDF".  @awoods perhaps anonymous resource "skolemized representation" could be documented in the API specification or the ontology?  

btw, the [spring consolidation](https://github.com/fcrepo4/fcrepo4/commit/b00873e7d47ecf9f266e3628fcb9270e35edcc9c) is what I initally observed to affect my implementation of the triplestore connector via a stand-alone activemq, as the [master context](https://github.com/fcrepo4/fcrepo4/commit/b00873e7d47ecf9f266e3628fcb9270e35edcc9c#diff-c6027a15cc414d0e7c2f52402fa5c2e8R8) has been changed.

**Comment by Surfrdan** [comment] 2023-12-13 16:51
Andrew started that his was non-breaking in the Jira issue if paid with another issue. Both of which were resolved and as Fedora 6 is now the LTS version, I'm closing this

**Closed by Surfrdan** 2023-12-13 16:51 UTC
